### PR TITLE
Decision trees Implemented

### PR DESCRIPTION
**Pull request by mihirneal**
Decision tree classifier trees implemented using scikit-learn

### CODE REVIEW

**Comment by aman190202** [comment]
Add the .png to the images folder and thus change the path in your Jupyter Notebook.

**Review by aman190202 — COMMENTED** [review]
Also, put up a link to your jupyter notebook from the README using the format "[hyperlink](path to notebook)"

**Comment by mihirneal** [comment]
ah! give me sec.

**Review by aman190202 — APPROVED** [review]

**Comment by mihirneal** [comment]
btw, I made the changes you requested.

**Pull request merged**
